build:
  version: "1.0.0"

spring:
  jpa:
    show-sql: true
  
  sql:
    init:
      mode: always

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eureka-server:8070/eureka/"


info:
  app:
    name: "account-service"
    version: "1.0.0"

metrics:
  tags:
    application: ${spring.application.name}


rabbitmq:
  template:
    retry:
      enabled: true
      initial-interval: 2s
      max-interval: 10s

logging:
  level:
    com:
      ashoumar:
        accounts: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 1000

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
        cancelRunningFuture: true
  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 100ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        ignoreExceptions:
          - java.lang.NullPointerException

    ratelimiter:
      configs:
        default:
          timeoutDuration: 500ms
          limitRefreshPeriod: 5s
          limitForPeriod: 5


