build:
  version: "1.0.0"

spring:
  jpa:
    show-sql: true

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eureka-server:8070/eureka/"


info:
  app:
    name: "card-service"
    version: "1.0.0"

metrics:
  tags:
    application: ${spring.application.name}


rabbitmq:
  template:
    retry:
      enabled: true
      initial-interval: 2s
      max-interval: 10s

logging:
  level:
    com:
      ashoumar:
        card_service: DEBUG
