build:
  version: "1.0.0"
  
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      httpclient: 
        connect-timeout: 1000
        response-timeout: 3s
  data:
    redis:
      connect-timeout: 2s
      timeout: 1s


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true  
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://eureka-server:8070/eureka/"


info:
  app:
    name: "gateway-server"
    version: "1.0.0"

metrics:
  tags:
    application: ${spring.application.name}


logging:
  level:
    com:
      ashoumar:
        gateway_server: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10s

